comment:
  layout: reach, changes, diff, files
  require_changes: coverage_drop OR uncovered_patch
coverage:
  ignore:
  - .*/settings_.*.py
  - .*/settings.py
  - .*/wsgi.py
  status:
    project:
      default:
        target: 90
    patch:
      default:
        target: 100
codecov:
  branch: main
  notify:
    # Wait for reasonable amount of tests to complete before
    # reporting coverage
    after_n_builds: 8
